# Generated by Django 6.0.1 on 2026-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_department_employee_timeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="cost_center_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="cost_center_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
