# Generated by Django 6.0.1 on 2026-02-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0003_employee_cost_center_code_employee_cost_center_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructor",
            options={
                "verbose_name": "Externer Mitarbeiter",
                "verbose_name_plural": "Externe Mitarbeiter",
            },
        ),
    ]
