# Generated by Django 6.0.1 on 2026-02-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_alter_leadstaging_status"),
        ("erp", "0012_invoice_email_sent_at"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="crm_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="crm.account",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="crm_opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="crm.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="erp_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="erp.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="erp_quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="erp.quote",
            ),
        ),
    ]
