# Generated by Django 6.0.1 on 2026-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_crm_account_project_crm_opportunity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="wip_limit_blocked",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_limit_done",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_limit_in_progress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_limit_todo",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
