# Generated by Django 6.0.1 on 2026-02-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_wip_limit_blocked_project_wip_limit_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="wip_limit_assignee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_limit_team",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
