# Generated by Django 6.0.1 on 2026-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_stockreceipt_product_competitor_price_net_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreceipt",
            name="invoice_file",
            field=models.FileField(
                blank=True, null=True, upload_to="erp/stock_receipts/"
            ),
        ),
    ]
