# Generated by Django 6.0.1 on 2026-02-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_stockreceipt_invoice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="erp.customer",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="event_number",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
