# Generated by Django 6.0.1 on 2026-02-07 14:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_course_customer_course_event_number_course_expenses"),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personnel.instructor",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor_daily_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="course",
            name="lodging",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="course",
            name="mobile_classroom_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="course",
            name="mobile_classroom_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mobile_classroom_courses",
                to="erp.product",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="mobile_classroom_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="price_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="course",
            name="price_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="course",
            name="required_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personnel.teachingskill",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=5
            ),
        ),
    ]
