# Generated by Django 6.0.1 on 2026-02-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_ai_status"),
        ("erp", "0006_course_instructor_course_instructor_daily_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="contracts.contract",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="erp.workorder",
            ),
        ),
    ]
