# Generated by Django 6.0.1 on 2026-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_course_contract_course_work_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Geplant"),
                    ("in_progress", "In Arbeit"),
                    ("done", "Abgeschlossen"),
                    ("cancelled", "Storniert"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
