# Generated by Django 6.0.1 on 2026-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_dunningnotice_is_locked_dunningnotice_locked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
