# Generated by Django 6.0.1 on 2026-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0013_productcategory_product_service_images"),
        ("personnel", "0004_alter_instructor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "verbose_name": "Veranstaltung",
                "verbose_name_plural": "Veranstaltungen",
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
        migrations.AddField(
            model_name="course",
            name="employees",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="personnel.employee"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="personnel.instructor"
            ),
        ),
    ]
