# Generated by Django 5.0.6 on 2025-12-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHighscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.IntegerField(default=1)),
                ('coins_collected', models.IntegerField(default=0)),
                ('time_played', models.IntegerField(default=0, help_text='Time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Highscore',
                'verbose_name_plural': 'Game Highscores',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
