# Generated by Django 5.0.6 on 2025-12-11 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusKongHighscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viruskong_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virus Kong Highscore',
                'verbose_name_plural': 'Virus Kong Highscores',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
