# Generated by Django 5.0.6 on 2025-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_systemsettings_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='imap_full_sync_completed',
            field=models.BooleanField(default=False, help_text='Whether initial full mailbox sync has been completed', verbose_name='Full Sync Completed'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_last_sync',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful email synchronization', null=True, verbose_name='Last Email Sync'),
        ),
    ]
