# Generated by Django 6.0.1 on 2026-02-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_auditlog_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="app_toggles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Enable/disable modules globally",
                verbose_name="App Toggles",
            ),
        ),
    ]
