# Generated by Django 6.0.1 on 2026-02-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0015_add_bedrock_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="marketing_approve_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Gruppen mit Freigaberechten (z.B. ["Orga","Manager"])',
                verbose_name="Marketing Approve Groups",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="marketing_edit_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Gruppen mit Schreibrechten (z.B. ["Manager"])',
                verbose_name="Marketing Edit Groups",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="marketing_view_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Gruppen mit Leserechten (z.B. ["Orga","Manager"])',
                verbose_name="Marketing View Groups",
            ),
        ),
    ]
