# Generated by Django 6.0.1 on 2026-02-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0016_systemsettings_marketing_approve_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="erp_edit_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Gruppen mit Schreibrechten (z.B. ["Manager"])',
                verbose_name="ERP Edit Groups",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="erp_view_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Gruppen mit Leserechten (z.B. ["Orga","Manager"])',
                verbose_name="ERP View Groups",
            ),
        ),
    ]
