# Generated by Django 6.0.1 on 2026-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0017_systemsettings_erp_edit_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="erp_min_margin_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                help_text="Mindestaufschlag in Prozent",
                max_digits=6,
                verbose_name="ERP Mindestmarge %",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="erp_undercut_max_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Maximaler Unterbietungsabstand in Prozent",
                max_digits=6,
                verbose_name="ERP Unterbieten Max %",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="erp_undercut_min_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                help_text="Minimaler Unterbietungsabstand in Prozent",
                max_digits=6,
                verbose_name="ERP Unterbieten Min %",
            ),
        ),
    ]
