# Generated by Django 6.0.1 on 2026-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0018_systemsettings_erp_min_margin_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="erp_competitor_accept_terms",
            field=models.BooleanField(
                default=False, verbose_name="ERP Konkurrenz-Provider TOS bestaetigt"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="erp_competitor_provider",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="ERP Konkurrenz-Provider",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="erp_competitor_scrape_enabled",
            field=models.BooleanField(
                default=False, verbose_name="ERP Konkurrenz-Scraper aktiv"
            ),
        ),
    ]
