# Generated by Django 6.0.1 on 2026-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0019_systemsettings_erp_competitor_accept_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="erp_competitor_api_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="ERP Konkurrenz API Key",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="erp_competitor_api_url",
            field=models.URLField(
                blank=True, default="", verbose_name="ERP Konkurrenz API URL"
            ),
        ),
    ]
