# Generated by Django 6.0.1 on 2026-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0020_systemsettings_erp_competitor_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="company_address",
            field=models.CharField(
                blank=True,
                help_text="Street and house number for outgoing letters",
                max_length=255,
                verbose_name="Company Address",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_city",
            field=models.CharField(
                blank=True,
                help_text="City for outgoing letters",
                max_length=100,
                verbose_name="Company City",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_country",
            field=models.CharField(
                blank=True,
                help_text="Country for outgoing letters",
                max_length=100,
                verbose_name="Company Country",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_email",
            field=models.EmailField(
                blank=True,
                help_text="Sender email used for invoices and dunning",
                max_length=254,
                verbose_name="Company Email",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_postal_code",
            field=models.CharField(
                blank=True,
                help_text="Postal code for outgoing letters",
                max_length=20,
                verbose_name="Company Postal Code",
            ),
        ),
    ]
