# Generated by Django 6.0.1 on 2026-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0021_systemsettings_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_auto_send",
            field=models.BooleanField(
                default=False,
                help_text="Mahnungsmails automatisch versenden",
                verbose_name="Auto Send Dunning Emails",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_days_level1",
            field=models.IntegerField(
                default=14,
                help_text="Tage nach Fälligkeit für Mahnstufe 1",
                verbose_name="Days Overdue (Level 1)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_days_level2",
            field=models.IntegerField(
                default=30,
                help_text="Tage nach Fälligkeit für Mahnstufe 2",
                verbose_name="Days Overdue (Level 2)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_days_level3",
            field=models.IntegerField(
                default=45,
                help_text="Tage nach Fälligkeit für Mahnstufe 3",
                verbose_name="Days Overdue (Level 3)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Automatisches Mahnwesen aktivieren",
                verbose_name="Enable Dunning",
            ),
        ),
    ]
