# Generated by Django 6.0.1 on 2026-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0022_systemsettings_dunning_auto_send_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="company_bank_name",
            field=models.CharField(
                blank=True,
                help_text="Bank name for payment details on invoices",
                max_length=255,
                verbose_name="Company Bank",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_bic",
            field=models.CharField(
                blank=True,
                help_text="BIC for payment details on invoices",
                max_length=64,
                verbose_name="Company BIC",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_iban",
            field=models.CharField(
                blank=True,
                help_text="IBAN for payment details on invoices",
                max_length=64,
                verbose_name="Company IBAN",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="invoice_auto_send",
            field=models.BooleanField(
                default=False,
                help_text="Rechnungen automatisch per Scheduler versenden",
                verbose_name="Auto Send Invoice Emails",
            ),
        ),
    ]
