# Generated by Django 6.0.1 on 2026-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0023_systemsettings_company_bank_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_email_body_template",
            field=models.TextField(
                blank=True,
                help_text="Platzhalter: {dunning_number}, {invoice_number}, {amount}, {due_date}, {customer_name}, {company_name}",
                verbose_name="Dunning Email Body Template",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="dunning_email_subject_template",
            field=models.CharField(
                blank=True,
                help_text='z.B. "Mahnung {dunning_number} zu Rechnung {invoice_number}"',
                max_length=255,
                verbose_name="Dunning Email Subject Template",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="invoice_email_body_template",
            field=models.TextField(
                blank=True,
                help_text="Platzhalter: {invoice_number}, {amount}, {due_date}, {customer_name}, {company_name}",
                verbose_name="Invoice Email Body Template",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="invoice_email_subject_template",
            field=models.CharField(
                blank=True,
                help_text='z.B. "Rechnung {invoice_number} von {company_name}"',
                max_length=255,
                verbose_name="Invoice Email Subject Template",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="scheduler_daily_time",
            field=models.TimeField(
                blank=True,
                help_text="z.B. 08:00",
                null=True,
                verbose_name="Scheduler Daily Time",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="scheduler_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Aktiviert den Zeitplan für Rechnungen und Mahnungen",
                verbose_name="Scheduler Enabled",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="scheduler_interval_minutes",
            field=models.IntegerField(
                default=60,
                help_text="z.B. alle 60 Minuten",
                verbose_name="Scheduler Interval Minutes",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="scheduler_last_run",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Scheduler Last Run"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="scheduler_mode",
            field=models.CharField(
                choices=[("daily", "Daily Time"), ("interval", "Interval Minutes")],
                default="daily",
                max_length=20,
                verbose_name="Scheduler Mode",
            ),
        ),
    ]
