# Generated by Django 6.0.1 on 2026-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0024_systemsettings_dunning_email_body_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="invoice_payment_days",
            field=models.IntegerField(
                default=14,
                help_text="Zahlungsziel in Tagen (für Rechnungen)",
                verbose_name="Invoice Payment Days",
            ),
        ),
    ]
