# Generated by Django 6.0.1 on 2026-02-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0025_systemsettings_invoice_payment_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("from_email", models.CharField(blank=True, max_length=255)),
                ("to_emails", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(blank=True, default="system", max_length=100),
                ),
            ],
        ),
    ]
