# Generated by Django 6.0.1 on 2026-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0026_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
