# Generated by Django 6.0.1 on 2026-02-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0027_emaillog_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="email_log_auto_archive_days",
            field=models.IntegerField(
                default=30,
                help_text="E-Mails älter als X Tage automatisch archivieren",
                verbose_name="Email Log Auto Archive Days",
            ),
        ),
    ]
