# Generated by Django 6.0.1 on 2026-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0028_systemsettings_email_log_auto_archive_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="company_version",
            field=models.CharField(
                default="1.0",
                help_text="Version for exported documents and guides.",
                max_length=50,
                verbose_name="Document Version",
            ),
        ),
    ]
