# Generated by Django 6.0.1 on 2026-02-03 13:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ABoroOffice', max_length=255, verbose_name='site name')),
                ('site_url', models.URLField(default='https://aboro.office', verbose_name='site URL')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255, verbose_name='email backend')),
                ('email_from', models.EmailField(default='noreply@aboro.office', max_length=254, verbose_name='email from')),
                ('email_host', models.CharField(blank=True, max_length=255, verbose_name='email host')),
                ('email_port', models.IntegerField(default=587, verbose_name='email port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='use TLS')),
                ('license_key', models.CharField(blank=True, help_text='Master license key for the system', max_length=255, verbose_name='license key')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='maintenance message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='ABoroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('support_agent', 'Support Agent'), ('customer', 'Customer'), ('classroom_manager', 'Classroom Manager'), ('approvals_officer', 'Approvals Officer')], db_index=True, default='customer', max_length=20, verbose_name='role')),
                ('support_level', models.IntegerField(blank=True, choices=[(1, 'Level 1 - Basic Support'), (2, 'Level 2 - Technical Support'), (3, 'Level 3 - Expert Support'), (4, 'Level 4 - Senior Expert / Team Lead')], help_text='Support level for agents (1-4). Only applicable for support_agent role.', null=True, verbose_name='support level')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='department')),
                ('is_agent', models.BooleanField(default=False, help_text='Whether this user is a support agent', verbose_name='is support agent')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this account', verbose_name='two factor enabled')),
                ('storage_quota_mb', models.IntegerField(default=1024, help_text='Total storage quota in MB', verbose_name='storage quota (MB)')),
                ('storage_used_mb', models.IntegerField(default=0, help_text='Current storage usage in MB', verbose_name='storage used (MB)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('user_timezone', models.CharField(default='Europe/Berlin', help_text='User timezone for scheduling and display', max_length=50, verbose_name='timezone')),
                ('microsoft_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Microsoft ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='location')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='street')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, null=True, verbose_name='country')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('force_password_change', models.BooleanField(default=False, help_text='If True, user must change password on next login', verbose_name='force password change on next login')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last time user was active', null=True, verbose_name='last activity')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ABoroOffice User',
                'verbose_name_plural': 'ABoroOffice Users',
                'indexes': [models.Index(fields=['email'], name='core_aborou_email_595b17_idx'), models.Index(fields=['username'], name='core_aborou_usernam_87c4e5_idx'), models.Index(fields=['role'], name='core_aborou_role_662f57_idx'), models.Index(fields=['is_active'], name='core_aborou_is_acti_73e4dd_idx'), models.Index(fields=['created_at'], name='core_aborou_created_1c4d68_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
