# Generated by Django 6.0.1 on 2026-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aborouser",
            name="is_approver",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user can approve SSH execution requests",
                verbose_name="is approver",
            ),
        ),
    ]
