# Generated by Django 6.0.1 on 2026-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist Completion',
                'verbose_name_plural': 'Checklist Completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the checklist item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description or instructions')),
                ('field_type', models.CharField(choices=[('checkbox', 'Simple checkbox'), ('soll_ist', 'Soll/Ist fields (e.g., 3 expected, 2 present)'), ('multi_check', 'Multiple checkboxes (e.g., Reset, Updates, Adopted)')], default='checkbox', help_text='What type of input field should be displayed?', max_length=20)),
                ('soll_label', models.CharField(blank=True, default='Soll', help_text='Label for Soll field (only for soll_ist)', max_length=100)),
                ('soll_value', models.CharField(blank=True, help_text="The Soll value (e.g., '13', '4,5,6,7,8', 'D1, D2, 1, 2, 3')", max_length=255)),
                ('ist_label', models.CharField(blank=True, default='Ist', help_text='Label for Ist field (only for soll_ist)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=True, help_text='For checkbox and multi_check items')),
                ('soll_value', models.CharField(blank=True, help_text="Soll value for soll_ist items (e.g., '3')", max_length=255)),
                ('ist_value', models.CharField(blank=True, help_text="Ist value for soll_ist items (e.g., '2')", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the item')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist Item Completion',
                'verbose_name_plural': 'Checklist Item Completions',
                'ordering': ['completion', 'item__order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Name of the option (e.g., 'Reset')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Item Option',
                'verbose_name_plural': 'Checklist Item Options',
                'ordering': ['item', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemOptionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, help_text='Whether this option was checked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Item Option Completion',
                'verbose_name_plural': 'Checklist Item Option Completions',
                'ordering': ['item_completion', 'option__order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the checklist (e.g., 'Technical Inspection AC')", max_length=255)),
                ('room_type', models.CharField(choices=[('AC', 'AC Classrooms'), ('HP', 'HP Classrooms'), ('both', 'Both (AC & HP)')], help_text='For which classroom types does this checklist apply?', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description or instructions for the checklist')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive checklists are not displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_start', models.DateField()),
                ('deployment_end', models.DateField()),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('confirmed_return', models.BooleanField(default=False, help_text='Confirmed that the classroom returns from the deployment location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classroom Deployments',
                'ordering': ['deployment_start'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('versand_geplant', 'Shipping planned'), ('versendet', 'Shipped'), ('abholung_geplant', 'Pickup planned'), ('zurueckgekommen', 'Returned')], help_text='Type of event', max_length=30)),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('notes', models.TextField(blank=True, help_text='Additional remarks or details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deployment History Entry',
                'verbose_name_plural': 'Deployment History Entries',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('versand', 'Shipping'), ('abholung', 'Pickup')], max_length=20)),
                ('send_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['send_date'],
            },
        ),
        migrations.CreateModel(
            name='MobileClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('HP', 'HP')], max_length=10)),
                ('status', models.CharField(choices=[('auf_lager', 'Auf Lager'), ('versandfertig', 'Versandfertig'), ('versand_geplant', 'Versand geplant'), ('an_standort', 'An Standort'), ('gesperrt', 'Gesperrt')], default='auf_lager', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks about issues or special status (e.g., Not picked up by DPD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mobile Classrooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('training', 'Training Site'), ('warehouse', 'Warehouse')], default='training', max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
