# Generated by Django 6.0.1 on 2026-02-03 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistcompletion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitemcompletion',
            name='completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_completions', to='classroom.checklistcompletion'),
        ),
        migrations.AddField(
            model_name='checklistitemcompletion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistitemoption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='classroom.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistitemoptioncompletion',
            name='item_completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_completions', to='classroom.checklistitemcompletion'),
        ),
        migrations.AddField(
            model_name='checklistitemoptioncompletion',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.checklistitemoption'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='classroom.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistcompletion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='classroom.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='deploymenthistory',
            name='deployment',
            field=models.ForeignKey(help_text='Associated deployment', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='classroom.classroomdeployment'),
        ),
        migrations.AddField(
            model_name='deploymenthistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailreminder',
            name='deployment',
            field=models.ForeignKey(blank=True, help_text='Deployment for which this reminder was created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='classroom.classroomdeployment'),
        ),
        migrations.AddField(
            model_name='emailreminder',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='classroom.mobileclassroom'),
        ),
        migrations.AddField(
            model_name='classroomdeployment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='classroom.mobileclassroom'),
        ),
        migrations.AddField(
            model_name='checklistcompletion',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to='classroom.mobileclassroom'),
        ),
        migrations.AddField(
            model_name='classroomdeployment',
            name='location',
            field=models.ForeignKey(help_text='Deployment site (training center or other location)', on_delete=django.db.models.deletion.PROTECT, to='classroom.shippingaddress'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemcompletion',
            unique_together={('completion', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemoption',
            unique_together={('item', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemoptioncompletion',
            unique_together={('item_completion', 'option')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='deploymenthistory',
            index=models.Index(fields=['deployment', '-event_date'], name='classroom_d_deploym_97abe9_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymenthistory',
            index=models.Index(fields=['event_type', 'event_date'], name='classroom_d_event_t_a75b00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailreminder',
            unique_together={('deployment', 'reminder_type', 'send_date')},
        ),
        migrations.AddIndex(
            model_name='checklistcompletion',
            index=models.Index(fields=['classroom', 'template'], name='classroom_c_classro_981b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistcompletion',
            index=models.Index(fields=['-completed_at'], name='classroom_c_complet_68255c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistcompletion',
            unique_together={('classroom', 'template')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomdeployment',
            unique_together={('classroom', 'deployment_start', 'deployment_end')},
        ),
    ]
