# Generated by Django 6.0.1 on 2026-02-03 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_deadline_hours', models.IntegerField(default=24, help_text='Hours until deadline (default: 24)')),
                ('approval_deadline_minutes', models.IntegerField(default=15, help_text='Minutes for final deadline (default: 15 = 07:15)')),
                ('reminder_1_time', models.TimeField(default='14:00', help_text='First reminder time (default: 14:00)')),
                ('reminder_2_time', models.TimeField(default='20:00', help_text='Second reminder time (default: 20:00)')),
                ('reminder_3_time', models.TimeField(default='07:00', help_text='Third/final reminder time next day (default: 07:00)')),
                ('ssh_timeout', models.IntegerField(default=900, help_text='SSH timeout in seconds (default: 900 = 15 min)')),
                ('email_from', models.EmailField(default='approvals@aboro.office', help_text='Email address to send from', max_length=254)),
                ('system_active', models.BooleanField(default=True, help_text='System active? (Inactive = no emails/SSH execution)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Last updated by', max_length=255)),
            ],
            options={
                'verbose_name': 'Approval System Settings',
                'verbose_name_plural': 'Approval System Settings',
            },
        ),
        migrations.CreateModel(
            name='RatingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(db_index=True, default='Training Environment', help_text='Display name (e.g., "Training Environment 02")', max_length=255)),
                ('server_url_prefix', models.CharField(default='02', help_text='Server number for URL (e.g., "02" for https://02.training.de)', max_length=2)),
                ('ssh_port', models.IntegerField(default=1425, help_text='SSH port for this server')),
                ('weekdays', models.JSONField(default=list, help_text='Days of week: 0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun')),
                ('abruf_zeit', models.TimeField(help_text='Execution time (e.g., 16:30)')),
                ('enabled', models.BooleanField(default=True, help_text='Enable this schedule')),
                ('approval_email_recipients', models.JSONField(blank=True, default=list, help_text='Email addresses for approval requests')),
                ('storage_location', models.CharField(blank=True, default='/var/www/reports', help_text='Local path for storing reports', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rating Schedule',
                'verbose_name_plural': 'Rating Schedules',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['enabled'], name='approvals_r_enabled_f92b6b_idx'), models.Index(fields=['display_name'], name='approvals_r_display_64346b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique approval token', unique=True)),
                ('server_name', models.CharField(db_index=True, help_text='Server name for approval', max_length=255)),
                ('server_port', models.IntegerField(default=1425, help_text='SSH port')),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='Email recipients for this approval')),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled execution time')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deadline', models.DateTimeField(help_text='Approval deadline (07:15 next day)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, help_text='Email, IP address, or "auto"', max_length=255, null=True)),
                ('approval_method', models.CharField(blank=True, choices=[('email', 'Email Link'), ('gui', 'GUI Button'), ('api', 'API')], max_length=20, null=True)),
                ('reminder_1_sent', models.BooleanField(default=False, help_text='14:00 reminder sent')),
                ('reminder_1_time', models.CharField(default='14:00', max_length=5)),
                ('reminder_2_sent', models.BooleanField(default=False, help_text='20:00 reminder sent')),
                ('reminder_2_time', models.CharField(default='20:00', max_length=5)),
                ('reminder_3_sent', models.BooleanField(default=False, help_text='07:00+1 day final reminder sent')),
                ('reminder_3_time', models.CharField(default='07:00', max_length=5)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('not_executed', 'Not Executed')], default='pending', max_length=20)),
                ('execution_output', models.TextField(blank=True)),
                ('execution_error', models.TextField(blank=True)),
                ('execution_exit_code', models.IntegerField(blank=True, null=True)),
                ('initial_email_sent', models.BooleanField(default=False)),
                ('final_summary_email_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('rating_schedule', models.ForeignKey(blank=True, help_text='Related rating schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='approvals.ratingschedule')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(db_index=True, help_text='Server name (e.g., "training-02")', max_length=255, unique=True)),
                ('server_url', models.URLField(help_text='Server URL for HTTP connectivity check')),
                ('ssh_port', models.IntegerField(default=22, help_text='SSH port for this server')),
                ('status', models.CharField(choices=[('healthy', 'Reachable'), ('unreachable', 'Unreachable'), ('unknown', 'Not tested')], default='unknown', max_length=20)),
                ('url_reachable', models.BooleanField(default=False, help_text='Is the URL reachable?')),
                ('ssh_reachable', models.BooleanField(default=False, help_text='Is SSH reachable?')),
                ('last_check', models.DateTimeField(blank=True, help_text='Last health check timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Health Check',
                'verbose_name_plural': 'Server Health Checks',
                'ordering': ['server_name'],
                'indexes': [models.Index(fields=['status'], name='approvals_s_status_500c1c_idx'), models.Index(fields=['server_name'], name='approvals_s_server__3d34b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.IntegerField(help_text='Reminder 1, 2, or 3')),
                ('reminder_time', models.CharField(help_text='Time sent (14:00, 20:00, 07:00)', max_length=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.TextField(help_text='Email recipients (JSON format)')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='approvals.approval')),
            ],
            options={
                'verbose_name': 'Approval Reminder',
                'verbose_name_plural': 'Approval Reminders',
                'ordering': ['-sent_at'],
                'unique_together': {('approval', 'reminder_number')},
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['token'], name='approvals_a_token_367d21_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status', 'deadline'], name='approvals_a_status_1fa43e_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['server_name', 'created_at'], name='approvals_a_server__52b4ab_idx'),
        ),
    ]
