# Generated by Django 6.0.1 on 2026-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_approval_audit_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="approvalauditlog",
            new_name="approvals_a_approva_4f70f0_idx",
            old_name="approvals_a_approv_4bdb2f_idx",
        ),
        migrations.RenameIndex(
            model_name="approvalauditlog",
            new_name="approvals_a_action_5dbea7_idx",
            old_name="approvals_a_action_1c0dbf_idx",
        ),
        migrations.AddField(
            model_name="approval",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
