# Generated by Django 6.0.1 on 2026-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentasset",
            name="brief",
            field=models.TextField(blank=True),
        ),
    ]
