# Generated by Django 6.0.1 on 2026-02-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_contentasset_brief"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="kpi_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="kpi_conversions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="kpi_impressions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="kpi_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="campaign",
            name="kpi_spend",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
