# Generated by Django 6.0.1 on 2026-02-06 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_campaign_kpi_clicks_campaign_kpi_conversions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Freigegeben"),
                            ("published", "Veröffentlicht"),
                            ("rejected", "Abgelehnt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("stamped_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="marketing.contentasset",
                    ),
                ),
                (
                    "stamped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
