# Generated by Django 6.0.1 on 2026-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_contentrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="last_kpi_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_kpi_conversions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_kpi_imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_kpi_impressions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_kpi_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_kpi_spend",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
