# Generated by Django 6.0.1 on 2026-02-07 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_campaign_last_kpi_clicks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignKpiSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_snapshots",
                        to="marketing.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
    ]
