# Generated by Django 6.0.1 on 2026-02-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_lead_scoring_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSourceProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("source", models.CharField(choices=[("handelsregister", "Handelsregister")], default="handelsregister", max_length=50)),
                ("keywords", models.CharField(default="IT Beratung", max_length=255)),
                ("keyword_mode", models.CharField(choices=[("all", "Alle enthalten"), ("min", "Mindestens ein Schlagwort"), ("exact", "Exakter Firmenname")], default="all", max_length=10)),
                ("search_type", models.CharField(default="n", max_length=1)),
                ("results_per_page", models.IntegerField(default=100)),
                ("register_art", models.CharField(blank=True, default="alle", max_length=10)),
                ("rechtsform", models.CharField(blank=True, max_length=10)),
                ("ort", models.CharField(blank=True, max_length=100)),
                ("postleitzahl", models.CharField(blank=True, max_length=10)),
                ("strasse", models.CharField(blank=True, max_length=200)),
                ("bundesland_bw", models.BooleanField(default=False)),
                ("bundesland_by", models.BooleanField(default=False)),
                ("bundesland_be", models.BooleanField(default=False)),
                ("bundesland_br", models.BooleanField(default=False)),
                ("bundesland_hb", models.BooleanField(default=False)),
                ("bundesland_hh", models.BooleanField(default=False)),
                ("bundesland_he", models.BooleanField(default=False)),
                ("bundesland_mv", models.BooleanField(default=False)),
                ("bundesland_ni", models.BooleanField(default=False)),
                ("bundesland_nw", models.BooleanField(default=False)),
                ("bundesland_rp", models.BooleanField(default=False)),
                ("bundesland_sl", models.BooleanField(default=False)),
                ("bundesland_sn", models.BooleanField(default=False)),
                ("bundesland_st", models.BooleanField(default=False)),
                ("bundesland_sh", models.BooleanField(default=False)),
                ("bundesland_th", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("schedule", models.CharField(choices=[("manual", "Manuell"), ("hourly", "Stündlich"), ("daily", "Täglich"), ("weekly", "Wöchentlich")], default="manual", max_length=10)),
                ("max_per_run", models.IntegerField(default=200)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeadImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("rate_limited", "Rate Limited"), ("failed", "Failed")], default="queued", max_length=20)),
                ("requested_count", models.IntegerField(default=0)),
                ("imported_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="crm.leadsourceprofile")),
            ],
        ),
        migrations.CreateModel(
            name="LeadStaging",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("source", models.CharField(default="Handelsregister", max_length=100)),
                ("status", models.CharField(choices=[("incomplete", "Unvollständig"), ("ready", "Bereit"), ("imported", "Importiert"), ("skipped", "Übersprungen")], default="incomplete", max_length=20)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staging_items", to="crm.leadsourceprofile")),
            ],
        ),
        migrations.CreateModel(
            name="SourceRequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(default="handelsregister", max_length=50)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
