# Generated by Django 6.0.1 on 2026-02-05 16:30

from django.db import migrations


def create_default_profile(apps, schema_editor):
    LeadSourceProfile = apps.get_model("crm", "LeadSourceProfile")
    if not LeadSourceProfile.objects.exists():
        LeadSourceProfile.objects.create(
            name="Handelsregister IT Beratung",
            source="handelsregister",
            keywords="IT Beratung",
            keyword_mode="all",
            schedule="manual",
            max_per_run=200,
        )


def remove_default_profile(apps, schema_editor):
    LeadSourceProfile = apps.get_model("crm", "LeadSourceProfile")
    LeadSourceProfile.objects.filter(name="Handelsregister IT Beratung").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_lead_sources"),
    ]

    operations = [
        migrations.RunPython(create_default_profile, remove_default_profile),
    ]
