# Generated by Django 6.0.1 on 2026-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_default_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadsourceprofile",
            name="niederlassung",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="leadsourceprofile",
            name="register_nummer",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="leadsourceprofile",
            name="register_gericht",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="leadsourceprofile",
            name="suchoptionen_aehnlich",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leadsourceprofile",
            name="suchoptionen_geloescht",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leadsourceprofile",
            name="suchoptionen_nur_zn_neuen_rechts",
            field=models.BooleanField(default=False),
        ),
    ]
