# Generated by Django 6.0.1 on 2026-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadstaging",
            name="lead_source",
            field=models.CharField(choices=[("web", "Website"), ("email", "E-Mail"), ("phone", "Telefon"), ("event", "Event"), ("referral", "Empfehlung"), ("other", "Sonstiges")], default="other", max_length=20),
        ),
        migrations.AddField(
            model_name="leadstaging",
            name="lead_status",
            field=models.CharField(choices=[("new", "Neu"), ("contacted", "Kontaktiert"), ("qualified", "Qualifiziert"), ("lost", "Verloren")], default="new", max_length=20),
        ),
    ]
