# Generated by Django 6.0.1 on 2026-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_staging_lead_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadstaging",
            name="enrichment_status",
            field=models.CharField(choices=[("pending", "Ausstehend"), ("enriched", "Angereichert"), ("no_match", "Keine Daten"), ("error", "Fehler")], default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="leadstaging",
            name="enrichment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leadstaging",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
