# Generated by Django 6.0.1 on 2026-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_lead_ai_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadstaging",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Unvollständig"),
                    ("ready", "Bereit"),
                    ("imported", "Importiert"),
                    ("skipped", "Übersprungen"),
                    ("needs_website", "Website gesucht"),
                ],
                default="incomplete",
                max_length=20,
            ),
        ),
    ]
