# Generated by Django 6.0.1 on 2026-02-03 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseProduct',
            fields=[
                ('code', models.CharField(help_text='Unique product code (e.g., ABORO_BASIC, CLASSROOM_STANDALONE)', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='product code')),
                ('name', models.CharField(help_text='Human-readable product name', max_length=255, verbose_name='product name')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('office', 'Office'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('on_premise', 'On-Premise'), ('standalone', 'Standalone')], default='office', max_length=20, verbose_name='tier')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for on-premise or if not applicable', max_digits=10, null=True, verbose_name='monthly price (EUR)')),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='yearly price (EUR)')),
                ('max_staff_users', models.IntegerField(default=1, help_text='Maximum number of staff/agent users. -1 for unlimited', verbose_name='max staff users')),
                ('max_total_users', models.IntegerField(default=10, help_text='Maximum total users. -1 for unlimited', verbose_name='max total users')),
                ('storage_quota_gb', models.IntegerField(default=10, help_text='Storage quota per user. -1 for unlimited', verbose_name='storage quota (GB)')),
                ('features', models.JSONField(default=dict, help_text='Dictionary of feature codes and their availability', verbose_name='features')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product can be purchased/used', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'License Product',
                'verbose_name_plural': 'License Products',
                'ordering': ['tier', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('license_code', models.CharField(help_text='Unique license code (auto-generated format)', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='license code')),
                ('customer_name', models.CharField(help_text='Organization/individual name', max_length=255, verbose_name='customer name')),
                ('customer_email', models.EmailField(help_text='Email for license notifications', max_length=254, verbose_name='customer email')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date the license was issued', verbose_name='issue date')),
                ('expiry_date', models.DateField(help_text='Date the license expires', verbose_name='expiry date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20, verbose_name='status')),
                ('instance_count', models.IntegerField(default=1, help_text='Number of instances this license covers (for standalone/on-premise)', verbose_name='instance count')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this license', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.licenseproduct', verbose_name='product')),
            ],
            options={
                'verbose_name': 'License Key',
                'verbose_name_plural': 'License Keys',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['status'], name='licensing_l_status_168c66_idx'), models.Index(fields=['expiry_date'], name='licensing_l_expiry__24dd98_idx'), models.Index(fields=['customer_email'], name='licensing_l_custome_09208c_idx')],
            },
        ),
    ]
