# Generated by Django 6.0.1 on 2026-02-07 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fibu", "0003_seed_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="FibuSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_posting_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_default_centers",
                        to="fibu.costcenter",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_expense_accounts",
                        to="fibu.account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_inventory_accounts",
                        to="fibu.account",
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_payable_accounts",
                        to="fibu.account",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_receivable_accounts",
                        to="fibu.account",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_revenue_accounts",
                        to="fibu.account",
                    ),
                ),
                (
                    "vat_output_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fibu_vat_output_accounts",
                        to="fibu.account",
                    ),
                ),
            ],
        ),
    ]
