# Generated by Django 6.0.1 on 2026-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("invoice_issued", "Invoice Issued"),
                    ("dunning_created", "Dunning Created"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("email", "Send Email"),
                    ("webhook", "Webhook Call"),
                    ("erp_update", "ERP Update"),
                    ("erp_invoice_email", "ERP Invoice Email"),
                    ("erp_dunning_email", "ERP Dunning Email"),
                ],
                default="email",
                max_length=50,
            ),
        ),
    ]
