# Generated by Django 6.0.1 on 2026-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_workflow_trigger_type_alter_workflowstep_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="trigger_filters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("invoice_issued", "Invoice Issued"),
                    ("dunning_created", "Dunning Created"),
                    ("erp_order_status", "ERP Order Status Changed"),
                    ("crm_lead_status", "CRM Lead Status Changed"),
                    ("crm_opportunity_stage", "CRM Opportunity Stage Changed"),
                    ("marketing_asset_status", "Marketing Asset Status Changed"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
    ]
